name: Java CI & CD

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'pom.xml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@release
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@release
      - name: Set up JDK 17
        uses: actions/setup-java@release
        with:
          java-version: 17
      - name: Cache local Maven repository
        uses: actions/cache@release
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Adding file name to path
        run: echo buildname=$(ls /home/runner/work/Lumbot/Lumbot/target | grep bot) >> $GITHUB_ENV

      - name: Upload to artifacts
        uses: actions/upload-artifact@release
        with:
          name: ${{ env.buildname }}
          path: target/${{ env.buildname }}
      - name: Upload to server
        run: |
          curl \
          -F 'buildfile=@target/${{ env.buildname }}' \
          https://${{ secrets.SSH_HOST }}/uploadlum.php?key=${{ secrets.UPLOAD_KEY }}
        shell: bash

      - name: Running remote script
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            python3 ~/downloadAndRestart.py ${{ env.buildname }}

          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}