name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
      - name: Upload to server
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: sftp://${{ secrets.SSH_HOST }}:${{ secrets.SSH_PORT }}/home/${{ secrets.SSH_USERNAME }}/lumbot/upload
          ftp-username: ${{ secrets.SSH_USERNAME }}
          ftp-password: ${{ secrets.SSH_PASSWORD }}
          local-dir: staging/
      - name: Restart Lum
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: python3 ~/lumbot/downloadAndRestart.py ${{secrets.GITHUB_TOKEN}}
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}