name: Melon Scanner Errors CD

on:
  push:
    branches:
      - main
    paths:
      - 'melonscannererrors.json'
      - '!src/**'
      - '!pom.xml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload to server
        uses: wei/curl@v1.1.1
        with:
          args: |
            -F 'melonscannererrors=@melonscannererrors.json' \
            https://srv1.slaynash.fr/uploadlum.php
      
      - name: Running remote script
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            python3 ~/downloadMelonscannererrors.py melonscannererrors.json

          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}